/* eslint-disable @typescript-eslint/ban-ts-comment */

// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from 'react'

export type RegistryIndexFile = { path: string; type: string; target?: string, content?: string }
export type RegistryIndexItem = {
    name: string
    description?: string
    type: string
    registryDependencies?: string[]
    files: RegistryIndexFile[]
    component: React.LazyExoticComponent<React.ComponentType<object>> | null
    categories?: string[]
    meta?: Record<string, unknown>
}

export const Index: Record<string, RegistryIndexItem> = {
    'action-button': {
        name: 'action-button',
        description: 'A button that displays a popup when clicked',
        type: 'registry:component',
        registryDependencies: ['button'],
        files: [
            { path: 'registry/new-york/components/action-button/action-button.tsx', type: 'registry:ui', target: '' },
            { path: 'registry/new-york/lib/constants.ts', type: 'registry:lib', target: '' },
        ],
        component: React.lazy(async () => {
            const mod = await import('@/registry/new-york/components/action-button/action-button.tsx')
            const exportName =
                Object.keys(mod).find(
                    (key) =>
                        typeof (mod as Record<string, unknown>)[key] === 'function' ||
                        typeof (mod as Record<string, unknown>)[key] === 'object'
                ) || 'action-button'
            return { default: (mod as Record<string, unknown>)[exportName] as React.ComponentType<object> }
        }),
        categories: undefined,
        meta: undefined,
    },
    'action-button-demo': {
        name: 'action-button-demo',
        description: '',
        type: 'registry:demo',
        registryDependencies: undefined,
        files: [{ path: 'registry/new-york/demos/action-button.demo.tsx', type: 'registry:demo', target: '' }],
        component: React.lazy(async () => {
            const mod = await import('@/registry/new-york/demos/action-button.demo.tsx')
            const exportName =
                Object.keys(mod).find(
                    (key) =>
                        typeof (mod as Record<string, unknown>)[key] === 'function' ||
                        typeof (mod as Record<string, unknown>)[key] === 'object'
                ) || 'action-button-demo'
            return { default: (mod as Record<string, unknown>)[exportName] as React.ComponentType<object> }
        }),
        categories: undefined,
        meta: undefined,
    },
}
